/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "IOModule.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(IOModule_PiMessage, IOModule_PiMessage, 2)


PB_BIND(IOModule_IOMessage, IOModule_IOMessage, 2)


PB_BIND(IOModule_RoundResetMsg, IOModule_RoundResetMsg, AUTO)


PB_BIND(IOModule_SetButtonLightsMsg, IOModule_SetButtonLightsMsg, AUTO)


PB_BIND(IOModule_SettingsMsg, IOModule_SettingsMsg, AUTO)


PB_BIND(IOModule_NormalModeMsg, IOModule_NormalModeMsg, AUTO)


PB_BIND(IOModule_CalibrateModeMsg, IOModule_CalibrateModeMsg, AUTO)


PB_BIND(IOModule_IndicateErrorMsg, IOModule_IndicateErrorMsg, AUTO)


PB_BIND(IOModule_StartSlideMsg, IOModule_StartSlideMsg, AUTO)


PB_BIND(IOModule_RemovePuckMsg, IOModule_RemovePuckMsg, AUTO)


PB_BIND(IOModule_SensorBlockedMsg, IOModule_SensorBlockedMsg, AUTO)


PB_BIND(IOModule_SensorClearedMsg, IOModule_SensorClearedMsg, AUTO)


PB_BIND(IOModule_LeftButtonPressedMsg, IOModule_LeftButtonPressedMsg, AUTO)


PB_BIND(IOModule_RightButtonPressedMsg, IOModule_RightButtonPressedMsg, AUTO)


PB_BIND(IOModule_AcceptButtonPressedMsg, IOModule_AcceptButtonPressedMsg, AUTO)


PB_BIND(IOModule_CancelButtonPressedMsg, IOModule_CancelButtonPressedMsg, AUTO)


PB_BIND(IOModule_GateScoreMsg, IOModule_GateScoreMsg, AUTO)


PB_BIND(IOModule_PuckInGateMsg, IOModule_PuckInGateMsg, AUTO)


PB_BIND(IOModule_SensorStateMsg, IOModule_SensorStateMsg, AUTO)


PB_BIND(IOModule_SetButtonRepeatMsg, IOModule_SetButtonRepeatMsg, AUTO)




